#!/bin/sh
# This trivially compiles all known-good configurations

# You can set env variables for the cross-compiler used for each architecture
DEFAULT_CROSS_COMPILE="/opt/arm-2011.03/bin/arm-none-eabi-"

PREFIX_lpc2104=${PREFIX_lpc2104:-$DEFAULT_CROSS_COMPILE}
PREFIX_lpc1343=${PREFIX_lpc1343:-$DEFAULT_CROSS_COMPILE}
PREFIX_versatile=${PREFIX_versatile:-$DEFAULT_CROSS_COMPILE}
PREFIX_atmega=${PREFIX_atmega:-avr-}

build_one () {
    make -s clean
    echo "####################"
    echo "Build for " "$1"
    echo "Cross compilier is \"$CROSS_COMPILE\""
    make -s -k MODE="$MAKEALL_MODE"
    test -f bathos.bin || echo "## Failed" >& 2
    test -f bathos && size bathos
    test -n "$T" && test -d "$T" && cp bathos $T/bathos-$1
}

for var in ARCH; do
    unset $var
done

# if se requested, save stuff in /tmp
if [ -n "$MAKEALL_SAVE" ]; then
    T=$(mktemp /tmp/bathos-makeall-XXXXXX)
    rm $T
    mkdir $T
else
    T=""
fi

for a in unix lpc2104 lpc1343 versatile atmega; do
    export ARCH=$a
    eval export CROSS_COMPILE="\${PREFIX_$(echo $ARCH | sed 's/-/_/g')}"
    # if there is bathos.lds, we have one mode only
    if [ -f arch-$a/bathos.lds ]; then
	unset MAKEALL_MODE
	build_one $a
    else
	for lds in $(echo arch-$a/bathos-*.lds); do
	    mode=$(echo $lds | sed -e 's/^.*bathos-//' -e 's/.lds$//')
	    export MAKEALL_MODE=$mode
	    build_one "$a-$mode"
	done
    fi
done

test -n "$T" && test -d "$T" && echo "Binaries saved to $T"
