
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <bathos/allocator.h>

static char ulong_fmt[100];

#ifndef min
#define min(a, b) ((a) < (b) ? (a) : (b))
#endif

static inline int __order_bitmap_len(int order)
{
	int nbits = BATHOS_NBUFS(order);
	int start_bit = __index_to_bit(0, order);
	int out = 0;

	if (start_bit % BITS_PER_LONG) {
		out++;
		nbits -= BITS_PER_LONG - (start_bit % BITS_PER_LONG);
	}
	if (nbits <= 0)
		return out;
	out += nbits / BITS_PER_LONG;
	if (nbits % BITS_PER_LONG)
		out++;

	return out;
}

static void __gen_bitmaps_lengths(void)
{
	int i;
	printf("const int PROGMEM __bitmap_len[] = {\n");
	for (i = 0; i < BATHOS_NORDERS; i++)
		printf("\t[%d] = %d,\n", i, __order_bitmap_len(i));
	printf("};\n\n");
}

static inline unsigned long *__order_to_mask(int order)
{
	int nbits = BATHOS_NBUFS(order);
	int start_bit = __index_to_bit(0, order);
	int i, bit_index, ls, le, lnbits;
	unsigned long *out = malloc(__order_bitmap_len(order) *
				    sizeof(unsigned long));

	memset(out, 0, __order_bitmap_len(order) * sizeof(unsigned long));

	for (i = 0, bit_index = 0; nbits > 0; i++,
		     nbits -= lnbits, bit_index += lnbits) {
		unsigned long long tmp;

		ls = (bit_index + start_bit) % BITS_PER_LONG;
		lnbits = min(nbits, BITS_PER_LONG - ls);
		le = ls + lnbits - 1;
		tmp = (1ULL << le) | ((1ULL << le) - 1);
		if (ls >= 1)
			tmp &= ~((1ULL << (ls)) - 1ULL);
		out[i] |= tmp;
	}
	return out;
}

static void __gen_masks_for_order(int order)
{
	int j;
	int l = __order_bitmap_len(order);
	unsigned long *m = __order_to_mask(order);
	char fmt[100];

	printf("static const unsigned long PROGMEM __bitmap_mask_%d[] = {\n",
	       order);
	snprintf(fmt, sizeof(fmt), "\t[%%d] = %s,\n", ulong_fmt);
	for (j = 0; j < l; j++)
		printf(fmt, j, m[j]);
	printf("};\n\n");
}

static void __gen_masks(void)
{
	int i;

	for (i = 0; i < BATHOS_NORDERS; i++)
		__gen_masks_for_order(i);

	printf("const unsigned long * const PROGMEM __bitmap_mask[] = {\n");
	for (i = 0; i < BATHOS_NORDERS; i++)
		printf("\t__bitmap_mask_%d,\n", i);
	printf("};\n\n");
}

static int __ffs(unsigned long x)
{
	int r = 1;

	if (!x)
		return 0;
#if BITS_PER_LONG == 64
	if ((x & 0xffffffff) == 0) {
		x >>= 32;
		r += 32;
	}
#endif
	if (!(x & 0xffff)) {
		x >>= 16;
		r += 16;
	}
	if (!(x & 0xff)) {
		x >>= 8;
		r += 8;
	}
	if (!(x & 0xf)) {
		x >>= 4;
		r += 4;
	}
	if (!(x & 3)) {
		x >>= 2;
		r += 2;
	}
	if (!(x & 1)) {
		x >>= 1;
		r += 1;
	}
	return r;
}

static void __gen_masks_ffs(void)
{
	int i;

	printf("const int PROGMEM __bitmap_mask_ffs[] = {\n");
	for (i = 0; i < BATHOS_NORDERS; i++) {
		unsigned long *m = __order_to_mask(i);
		printf("\t[%d] = %d,\n", i, __ffs(m[0])  - 1);
	}
	printf("};\n");

}

/*
 * Generate bitmaps and bitmaps masks
 */
int main(int argc, char *argv[])
{
	printf("/* This file was generated by %s */\n", argv[0]);
	printf("/* It contains various tables for the bathos buddy allocator */\n");
	printf("/* Orders: %d, Size = %d*/\n",
	       BATHOS_NORDERS, BATHOS_ALLOCATOR_MEMORY);
	printf("#include <stdint.h>\n");
	printf("#include <arch/bathos-arch.h>\n");
	printf("\n");
	sprintf(ulong_fmt, "0x%%0%ullx", (BITS_PER_LONG/8)*2);
	__gen_bitmaps_lengths();
	__gen_masks();
	__gen_masks_ffs();
	return 0;
}
