#!/bin/bash
# gen_gpios_names: generate object file with gpio labels
# set -x

[ $# -lt 3 ] && \
    { echo "Use $0 <obj-format> <gpio_cfg_file> <output_obj_file>" ; exit 1 ; }

f=$(tempfile)
r=$(tempfile)
fmt=$1
out=$3

cat $2 | sed -e 's/^[ \t]*#.*//' | cut -d ',' -f 1 | tr -d '\n' | tr -d '"' > $f

for s in start end size ; do
    echo "_binary_$(echo $f | sed -e 's/\//_/g')_$s gpio_labels_$s" >> $r
done

ret=0

${OBJCOPY} --redefine-syms=$r -I binary -O $fmt $f $out || ret=1
${OBJCOPY} --rename-section \
    .data=.text.gpio-labels,contents,alloc,load,readonly,code $out $out || \
    ret=1

rm $f $r

exit $ret

